import type { ProcessFlowDefinition } from '@/sdk'

export const inventoryProcessFlow = {
  title: 'Inventory Process Flow',
  description:
    'How shared records, stock settings, adjustments, balances, and movement ledgers work together in OneDayOS.',
  steps: [
    {
      id: 'shared-records-setup',
      number: 1,
      title: 'Shared Records',
      description:
        'Products and Warehouses are created as shared Records before Inventory references them.',
      inputs: ['Shared Product records', 'Shared Warehouse records'],
      outputs: ['Reusable Product and Warehouse identities'],
      warning: 'Inventory does not own Product, ProductCategory, Warehouse, or Supplier identity.',
      status: 'current',
    },
    {
      id: 'inventory-product-settings',
      number: 2,
      title: 'Inventory Tracking Settings',
      description:
        'Inventory extends shared Products with stock tracking and reorder point settings stored in InventoryProductExtension.',
      inputs: ['Shared Product', 'Stock tracking setting', 'Reorder point'],
      outputs: ['InventoryProductExtension for the shared Product'],
      warning: 'Inventory settings must not duplicate Product code, name, unit, category, or Supplier identity.',
      status: 'current',
    },
    {
      id: 'stock-adjustment',
      number: 3,
      title: 'Stock Adjustment',
      description:
        'A user posts an opening balance or manual correction. The server validates Product and Warehouse ownership, computes previous and new quantities, and prevents negative resulting stock.',
      inputs: ['Product', 'Warehouse', 'New quantity', 'Reason', 'Optional notes'],
      outputs: ['Validated stock adjustment intent'],
      warning: 'Client-computed previous quantity, new quantity, and balance-after values are not accepted as source of truth.',
      status: 'current',
    },
    {
      id: 'transactional-posting',
      number: 4,
      title: 'Transactional Posting',
      description:
        'One stock adjustment creates the StockAdjustment, appends a StockMovement, and updates or creates StockBalance together in a transaction.',
      inputs: ['Validated Product and Warehouse', 'Server-computed quantity delta', 'Posting user'],
      outputs: ['StockAdjustment', 'StockMovement', 'StockBalance update or creation'],
      warning: 'If any persistence step fails, no adjustment, movement, balance update, or success event should remain.',
      status: 'current',
    },
    {
      id: 'stock-balance',
      number: 5,
      title: 'Stock Balance',
      description:
        'StockBalance stores the current quantity by Product and Warehouse. Users read this operational state through Stock Levels.',
      inputs: ['Successful posting transaction'],
      outputs: ['Current quantity by shared Product and Warehouse'],
      warning: 'StockBalance is not directly edited by users.',
      status: 'current',
    },
    {
      id: 'stock-movement-ledger',
      number: 6,
      title: 'Stock Movement Ledger',
      description:
        'StockMovement is the append-only ledger of Inventory changes. Users read it through Stock Movements for investigation and reconciliation.',
      inputs: ['Successful posting transaction'],
      outputs: ['Immutable stock movement entry with resulting quantity and source reference'],
      warning: 'Movements are not normal editable records in this MVP.',
      status: 'current',
    },
    {
      id: 'low-stock-detection',
      number: 7,
      title: 'Low-Stock Detection',
      description:
        'Stock Levels compare current quantity with the reorder point from InventoryProductExtension and show low-stock status with text.',
      inputs: ['StockBalance quantity', 'InventoryProductExtension reorder point'],
      outputs: ['Low-stock visual and text status'],
      warning: 'No Notification Service exists in this MVP; low stock is a visible status and event only.',
      status: 'current',
    },
  ],
  connections: [
    { from: 'shared-records-setup', to: 'inventory-product-settings' },
    { from: 'inventory-product-settings', to: 'stock-adjustment' },
    { from: 'stock-adjustment', to: 'transactional-posting' },
    { from: 'transactional-posting', to: 'stock-balance', label: 'updates together' },
    { from: 'transactional-posting', to: 'stock-movement-ledger', label: 'appends together' },
    { from: 'stock-movement-ledger', to: 'low-stock-detection' },
  ],
  plannedLabel: 'Planned for Inventory V2 — not implemented in the current demo',
  plannedSteps: [
    {
      id: 'planned-receipts',
      title: 'Receipts',
      description: 'Planned inbound stock workflow referencing a shared Supplier and destination Warehouse.',
      status: 'planned',
    },
    {
      id: 'planned-issues',
      title: 'Issues',
      description: 'Planned outbound stock workflow with an optional shared Customer reference.',
      status: 'planned',
    },
    {
      id: 'planned-transfers',
      title: 'Transfers',
      description: 'Planned paired movement between source and destination Warehouses.',
      status: 'planned',
    },
  ],
  owns: [
    'InventoryProductExtension',
    'StockBalance',
    'StockMovement',
    'StockAdjustment',
  ],
  doesNotOwn: [
    'Product',
    'ProductCategory',
    'Supplier',
    'Warehouse',
    'Customer',
    'Employee',
  ],
  currentBoundaries: [
    'Inventory supports manual stock adjustments, current stock levels, product stock settings, movement history, and low-stock visual status.',
    'Inventory does not create or own Product, ProductCategory, Supplier, Warehouse, Customer, or Employee identity.',
    'Inventory does not directly edit StockBalance or StockMovement through normal UI routes.',
    'Inventory does not yet implement Receipts, Issues, Transfers, purchasing, sales, approvals, notifications, accounting, or background jobs.',
  ],
  futureIntegrations: [
    'Purchasing may later provide source documents for approved Receipt workflows.',
    'Sales or fulfillment may later provide source documents for approved Issue workflows.',
    'Notifications may later subscribe to low-stock events.',
    'These are future integration directions, not active modules or current demo behavior.',
  ],
} as const satisfies ProcessFlowDefinition

export function inventoryProcessFlowForRuntime(inventoryV2Enabled: boolean): ProcessFlowDefinition {
  if (!inventoryV2Enabled) return inventoryProcessFlow

  return {
    ...inventoryProcessFlow,
    description:
      'How shared records feed canonical Receipt, Issue, Transfer, and Adjustment posting, balances, the movement ledger, and low-stock detection.',
    steps: [
      {
        id: 'shared-records-setup',
        number: 1,
        title: 'Shared Records',
        description: 'Products, Suppliers, Customers, and Warehouses remain shared organization records referenced by Inventory.',
        inputs: ['Shared Products', 'Shared Suppliers and Customers', 'Shared Warehouses'],
        outputs: ['Reusable tenant-scoped identities'],
        warning: 'Inventory references these records and does not own or mutate their identity.',
        status: 'current',
      },
      {
        id: 'receipt',
        number: 2,
        title: 'Receipt',
        description: 'Receipts add stock to a destination Warehouse with an optional shared Supplier reference.',
        inputs: ['Destination Warehouse', 'Product lines', 'Optional Supplier'],
        outputs: ['Posted Receipt and inbound movements'],
        status: 'current',
      },
      {
        id: 'issue',
        number: 3,
        title: 'Issue',
        description: 'Issues remove available stock from a source Warehouse with an optional shared Customer reference.',
        inputs: ['Source Warehouse', 'Product lines', 'Optional Customer'],
        outputs: ['Posted Issue and outbound movements'],
        warning: 'The complete transaction is rejected when any line would create negative stock.',
        status: 'current',
      },
      {
        id: 'transfer',
        number: 4,
        title: 'Transfer',
        description: 'Transfers move stock between different Warehouses using balanced outbound and inbound movements.',
        inputs: ['Source Warehouse', 'Destination Warehouse', 'Product lines'],
        outputs: ['Posted Transfer and paired movements'],
        warning: 'Transfers do not change organization-wide inbound or outbound totals.',
        status: 'current',
      },
      {
        id: 'adjustment',
        number: 5,
        title: 'Adjustment',
        description: 'Adjustments record counted final quantities while the server computes exact movement deltas.',
        inputs: ['Warehouse', 'Counted Product quantities', 'Reason'],
        outputs: ['Posted Adjustment and computed movements'],
        status: 'current',
      },
      {
        id: 'transactional-posting',
        number: 6,
        title: 'Transactional Posting',
        description: 'Canonical headers, lines, movements, and balances post atomically with idempotency and safe reversal.',
        inputs: ['Validated transaction intent', 'Posting user'],
        outputs: ['Immutable canonical transaction history'],
        warning: 'Posted records are read-only; corrections use a separately posted reversal or new transaction.',
        status: 'current',
      },
      {
        id: 'stock-balance',
        number: 7,
        title: 'Stock Balance',
        description: 'StockBalance remains the authoritative current quantity for every Product and Warehouse.',
        inputs: ['Successful canonical posting'],
        outputs: ['Current stock levels'],
        status: 'current',
      },
      {
        id: 'stock-movement-ledger',
        number: 8,
        title: 'Movement Ledger and Low-Stock Detection',
        description: 'The append-only ledger explains every balance change; Stock Levels compare totals with reorder points.',
        inputs: ['Canonical movements', 'Inventory tracking settings'],
        outputs: ['Auditable movement history', 'Visible low-stock state'],
        warning: 'Low stock is a visible status only; no Notification Service is claimed.',
        status: 'current',
      },
    ],
    connections: [
      { from: 'shared-records-setup', to: 'receipt' },
      { from: 'shared-records-setup', to: 'issue' },
      { from: 'shared-records-setup', to: 'transfer' },
      { from: 'shared-records-setup', to: 'adjustment' },
      { from: 'receipt', to: 'transactional-posting' },
      { from: 'issue', to: 'transactional-posting' },
      { from: 'transfer', to: 'transactional-posting' },
      { from: 'adjustment', to: 'transactional-posting' },
      { from: 'transactional-posting', to: 'stock-balance', label: 'updates atomically' },
      { from: 'transactional-posting', to: 'stock-movement-ledger', label: 'appends atomically' },
    ],
    plannedLabel: 'Canonical Inventory V2 workflows are current in the controlled cutover.',
    plannedSteps: [],
    owns: [
      'InventoryProductExtension',
      'StockBalance',
      'StockMovement',
      'StockAdjustment',
      'InventoryTransaction',
      'InventoryTransactionLine',
    ],
    currentBoundaries: [
      'Inventory supports canonical Receipts, Issues, Transfers, Adjustments, reversals, Stock Levels, and Movement Ledger review.',
      'Shared Product, Category, Supplier, Customer, and Warehouse identity remains outside Inventory ownership.',
      'Purchasing, Sales, approvals, notifications, accounting, and workflow automation remain outside this cutover.',
    ],
  }
}
