import type { ModuleUxContract } from '@/sdk'

export const inventoryUx = {
  primaryUsers: [
    'Warehouse staff who review stock levels and post count corrections.',
    'Inventory supervisors who monitor low-stock pressure and reconcile stock movement history.',
    'Org Admin users who configure Inventory access and perform administrative Inventory tasks.',
  ],
  userGoals: [
    'Know current stock quantity by shared Product and Warehouse.',
    'Detect products that are below reorder point before operational work is blocked.',
    'Post stock corrections safely from physical count or opening balance information.',
    'Understand why stock increased or decreased through the movement ledger.',
    'Configure Inventory-specific tracking settings for shared Products.',
  ],
  primaryTasks: [
    'Open the Inventory Dashboard.',
    'Review tracked products and low-stock products.',
    'Review Stock Levels by Product and Warehouse.',
    'Post a Stock Adjustment.',
    'Review Stock Movements as an append-only ledger.',
    'Update Product Settings for stock tracking and reorder point.',
    'Open shared Product or Warehouse records when identity details need review.',
    'Review Inventory Process Flow to understand the module boundary and posting behavior.',
  ],
  taskFrequency: [
    'Stock-level review is a frequent operational task.',
    'Stock adjustment is performed when physical counts, opening balances, or corrections require it.',
    'Product-setting review is an occasional administrative task.',
    'Movement review is an investigation and reconciliation task.',
    'Process Flow review is used for onboarding, training, and workflow clarification.',
  ],
  workEnvironment: [
    'Desktop or shared workstation in warehouse or office contexts.',
    'Operational users may be interrupted and must recover page context quickly.',
    'Tables must support repeated scanning, comparison, and quick verification.',
    'Forms must prevent costly posting mistakes before submission.',
  ],
  requiredKnowledge: [
    'Product identity, code, and unit are managed as shared Records.',
    'Warehouse identity is managed as a shared Record.',
    'Inventory owns stock behavior, not Product or Warehouse identity.',
    'A posted adjustment creates an adjustment record, a movement ledger entry, and a current balance update together.',
    'Current quantity shown in the form is context only; the server computes final posting values.',
  ],
  relatedBusinessObjects: [
    'Product',
    'ProductCategory',
    'Supplier',
    'Warehouse',
  ],
  moduleOwnedRecords: [
    'InventoryProductExtension',
    'StockBalance',
    'StockMovement',
    'StockAdjustment',
  ],
  criticalErrorsToPrevent: [
    'Posting an adjustment to the wrong Warehouse.',
    'Using a Product or Warehouse outside the current organization.',
    'Reducing stock below zero.',
    'Accepting client-computed previous quantity, new quantity, or balance-after values.',
    'Partially creating StockAdjustment, StockMovement, or StockBalance changes.',
    'Emitting success events after failed persistence.',
    'Making Product or Warehouse appear Inventory-owned.',
  ],
  permissionRoles: [
    'Inventory read user: can open Inventory overview, stock levels, product settings, movements, and adjustment history according to assigned read permissions.',
    'Inventory adjustment operator: can post manual stock adjustments when granted stock-adjustment create permission.',
    'Inventory supervisor: can review stock pressure, investigate movement history, and configure product tracking settings when granted update permission.',
    'Org Admin: can administer access and perform Inventory work when permissions and module enablement allow it.',
  ],
  appNavigation: [
    'Dashboard',
    'Process Flow',
    'Product Settings',
    'Stock Levels',
    'Stock Movements',
    'Stock Adjustments',
    'Related Records: Products, Categories, Suppliers, Warehouses',
  ],
  pageMap: [
    '/[orgSlug]/inventory - Inventory Dashboard with real tracked, low-stock, warehouse, movement, and adjustment summaries.',
    '/[orgSlug]/inventory/process-flow - Explanation of shared Records, settings, posting, balances, ledger, low-stock detection, and deferred integrations.',
    '/[orgSlug]/inventory/product-settings - Inventory-specific settings for shared Products.',
    '/[orgSlug]/inventory/stock-levels - Current StockBalance rows by shared Product and Warehouse.',
    '/[orgSlug]/inventory/stock-movements - Append-only StockMovement ledger.',
    '/[orgSlug]/inventory/stock-adjustments - Posted manual StockAdjustment records.',
    '/[orgSlug]/inventory/stock-adjustments/new - Manual stock adjustment form.',
  ],
  defaultLandingPage: '/[orgSlug]/inventory',
  processFlowRoute: '/[orgSlug]/inventory/process-flow',
  keyboardWorkflows: [
    'Navigate the app launcher and Inventory sidebar with keyboard focus.',
    'Reach the New Adjustment primary action from Dashboard, Stock Levels, or Stock Adjustments.',
    'Move through Product, Warehouse, Current Quantity, New Quantity, Reason, Notes, and actions in logical form order.',
    'Submit or cancel the adjustment without using a mouse.',
    'Open profile and app switcher menus, then close them with supported keyboard behavior.',
  ],
  accessibilityRequirements: [
    'Low-stock and tracking status must be communicated with text, not color alone.',
    'Inventory forms must provide labels, descriptions, and recoverable validation errors.',
    'Focus must remain visible in sidebar, tables, links, buttons, menus, and forms.',
    'Tables must use semantic headers and concise cell text for scanning.',
    'Process Flow must be readable in sequence without relying only on arrows or color.',
    'Error states must explain recovery without exposing provider, SQL, Prisma, or stack details.',
    'Permission denied and module unavailable states must be visually and semantically distinct.',
  ],
  usabilityTestScenarios: [
    'Find the current quantity of Coffee Beans in Stock Levels.',
    'Explain why Coffee Beans is shown as low stock.',
    'Add stock safely through New Adjustment.',
    'Find the corresponding Stock Movement entry after posting.',
    'Open the shared Product record from Inventory context when identity details need review.',
    'Return from shared Records to Inventory through the app shell.',
    'Explain the Inventory process using Process Flow.',
    'Attempt an adjustment that would make stock negative and understand the error.',
  ],
  knownMvpLimitations: [
    'No purchasing receipt integration.',
    'No sales or outbound stock integration.',
    'No stock transfers.',
    'No lots or serial numbers.',
    'No expiry tracking.',
    'No valuation or costing.',
    'No notifications.',
    'No attachments or comments.',
    'No import/export engine.',
    'No advanced reporting or global search.',
  ],
  futureIntegrations: [
    'Purchasing receipts that post inbound StockMovements.',
    'Sales or fulfillment flows that post outbound StockMovements.',
    'Notification Service subscription for low-stock events.',
    'Reporting Service for inventory analysis.',
    'Import/Export Engine for controlled bulk setup.',
    'Background jobs only if future operational volume justifies them.',
  ],
} as const satisfies ModuleUxContract
