export const dependencyAuditPolicy = {
  advisoryId: 'GHSA-mh99-v99m-4gvg',
  advisoryUrl: 'https://github.com/advisories/GHSA-mh99-v99m-4gvg',
  package: 'brace-expansion',
  severity: 'high',
  reviewBy: '2026-08-31T23:59:59.999Z',
  owner: 'Platform Security',
  rationale: 'Temporary dev-only exception for the current stable ESLint and Next lint-plugin graph.',
  removalConditions: [
    'eslint or eslint-config-next changes',
    '@eslint, eslint-plugin, minimatch, or brace-expansion changes',
    'Next lint integration or advisory metadata changes',
    'a coherent stable patched lint stack becomes available',
  ],
  expectedVulnerabilityEntries: [
    '@eslint/config-array',
    '@eslint/eslintrc',
    'brace-expansion',
    'eslint',
    'eslint-config-next',
    'eslint-plugin-import',
    'eslint-plugin-jsx-a11y',
    'eslint-plugin-react',
    'minimatch',
  ],
  expectedVersions: {
    eslint: '9.39.4',
    'eslint-config-next': '16.2.11',
    'eslint-plugin-import': '2.32.0',
    'eslint-plugin-jsx-a11y': '6.10.2',
    'eslint-plugin-react': '7.37.5',
    minimatch: '3.1.5',
    'brace-expansion': '1.1.16',
  },
} as const
